app/conf/urls.py
#encoding: utf-8

from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.views.generic.base import RedirectView

urlpatterns = patterns('',
    url(r'^$', RedirectView.as_view(url='/movies/',permanent=True), name='index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^movies/', include('movies.urls', namespace='movies')),
)

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

app/movies/urls.py
#encoding: utf-8

from django.conf.urls import include, url, patterns

urlpatterns = patterns('movies.views',
	url(r'^$','index', name='home'),
	url(r'^agendar/(?P<pk>\d+)$','add_scheduled_movie', name='scheduled_movie'),
	url(r'^apagar_filme/(?P<pk>\d+)$','movie_delete', name='delete_movie'),
	url(r'^editar_filme/(?P<pk>\d+)$', 'update_movie', name='edit_movie'),
	url(r'^novo_filme/$','add_movie', name='create_movie'),
)

app/core/models.py
#encoding: utf-8

from django.db import models
from core.tasks import async_email



class Directors(models.Model):
	'''
	This class is responsible for mapping the directors table.
	'''	
	id_director = models.AutoField(primary_key=True, verbose_name=u'Cod Diretor', db_column='id_director')
	name = models.CharField(max_length=100, verbose_name=u'Nome', db_column='name', unique=True)
	description = models.TextField(verbose_name=u'Descrição', db_column='description',blank=True,
		null=True, default='')
	created_at = models.DateTimeField(auto_now_add=True, db_column='created_at', blank=False, verbose_name=u'Criado em')
	updated_at = models.DateTimeField(verbose_name=u'Atualizado em', auto_now=True, db_column='updated_at')

	def __unicode__(self):
		return u'%s' % self.name

	class Meta:
		verbose_name=u'Diretor'
		verbose_name_plural=u'Diretores'
		db_table='director'
		ordering=['id_director']



class Movies(models.Model):
	'''
	This class is responsible for mapping the movies table.
	'''
	id_movie = models.AutoField(primary_key=True, verbose_name=u'Cod Filme', db_column='id_movie')
	name = models.CharField(max_length=100, verbose_name=u'Nome', db_column='name', unique=True)
	director = models.ForeignKey(Directors, verbose_name=u'Diretor', related_name='movies_director', 
		on_delete=models.PROTECT)
	note = models.IntegerField(verbose_name='Nota', db_column='note', blank=True, null=True,
		default=0)
	img = models.ImageField(upload_to='img/movies')
	description = models.TextField(verbose_name=u'Descrição', db_column='description',blank=True,
		null=True, default='')
	status = models.BooleanField(verbose_name=u'Status', db_column='status', default=True, blank=True)
	created_at = models.DateTimeField(auto_now_add=True, db_column='created_at', blank=False, verbose_name=u'Criado em')
	updated_at = models.DateTimeField(verbose_name=u'Atualizado em', auto_now=True, db_column='updated_at')


	def __unicode__(self):
		return u'%s' % self.name

	@models.permalink
	def get_delete_url(self):
		return ('movies:delete_movie', [int(self.pk)], {})

	@models.permalink
	def get_update_url(self):
		return ('movies:edit_movie', [int(self.pk)], {})		


	class Meta:
		verbose_name=u'Filme'
		verbose_name_plural=u'Filmes'
		db_table='movies'
		ordering=['id_movie']



class ScheduledMovies(models.Model):
	'''
	This class is responsible for mapping the ScheduledMovies table.
	'''
	id_scheduled_movie = models.AutoField(primary_key=True, verbose_name=u'Cod Agendamento', db_column='id_scheduled_movie')
	name = models.CharField(max_length=100, verbose_name=u'Nome', db_column='name')
	movie = models.ForeignKey(Movies, verbose_name=u'Filme', related_name='scheduled_movies', 
		on_delete=models.PROTECT)
	created_at = models.DateTimeField(db_column='created_at', blank=False, verbose_name=u'Data')

	def __unicode__(self):
		return u'%s' % self.name

	class Meta:
		verbose_name=u'Agendamento'
		verbose_name_plural=u'Agendamentos'
		db_table='scheduled_movies'
		ordering=['id_scheduled_movie']



def post_save_reply(created, instance, **kwargs):
	async_email.delay(instance)
	
models.signals.post_save.connect(
	post_save_reply, sender=ScheduledMovies, dispatch_uid='post_save_reply'
)			

app/movies/forms.py
#encoding: utf-8

from django import forms
from core.models import Movies, ScheduledMovies



class MovieForm(forms.ModelForm):
    '''
    This class is responsible generator form MovieForm.
    '''
    class Meta:
        model = Movies

class ScheduledMoviesForm(forms.ModelForm):
    '''
    This class is responsible generator form ScheduledMoviesForm.
    '''
    class Meta:
        model = ScheduledMovies

app/movies/views.py
#encoding: utf-8

from core.models import Movies
from movies.forms import MovieForm, ScheduledMoviesForm
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.contrib import messages
from django.core.paginator import Paginator
from django.core.paginator import PageNotAnInteger
from django.db.models.deletion import ProtectedError



def add_scheduled_movie(request, pk):
	'''
	This function responsive tratament create new scheduled movie.
	'''	
	template = 'movies/scheduled_movie.html'
	movie = get_object_or_404(Movies, pk=pk)
	form = ScheduledMoviesForm(request.POST or None)

	if form.is_valid():
		form.save()
		form = ScheduledMoviesForm()
		messages.success(request, 'Agendado com sucesso.')
	context = {'movie': movie,'form': form,}

	return render(request,template, context)



class MoviesListView(ListView):
	'''
	this class is responsible for returning the lists of Movies.
	'''
	model = Movies
	paginate_by = 12
	template_name = 'movies/list_movies.html'

	def get_queryset(self):
		qs = Movies.objects.filter(status=True)
		search = self.request.GET.get('search', '')
		if search != '':
			qs = qs.filter(name__icontains=search)
		return qs		



class MovieAddView(CreateView):
	'''
	This class responsive tratament create new Movie.
	'''
	model = Movies
	form_class = MovieForm
	template_name = 'movies/create_movie.html'
	success_url = reverse_lazy('movies:create_movie')

	def get_context_data(self, **kwargs):
		context = super(MovieAddView, self).get_context_data(**kwargs)
		contact_list = self.get_queryset()

		paginator = Paginator(contact_list, 12)
		try: 
			page = self.request.GET.get("page",'1')
		except ValueError: 
			page = 1

		try:
			contact_list = paginator.page(page)
		except (InvalidPage, EmptyPage):
			contact_list = paginator.page(paginator.num_pages)

		context.update({'object_list':contact_list,'page_obj': contact_list}) 
		return context    



class MovieEditView(UpdateView):
	'''
	This class is responsible treatment edit Movie.
	'''
	model = Movies
	form_class = MovieForm
	template_name = 'movies/edit_movie.html'
	success_url = reverse_lazy('movies:create_movie')

	def form_valid(self, form):
		self.object = form.save()
		messages.success(self.request, 'Alterado com sucesso.')
		return HttpResponseRedirect(self.object.get_update_url())



class MovieDeleteView(DeleteView):
	'''
	This class is responsible for making treatment to exclude a single object
	Movies.
	'''
	model = Movies
	template_name = 'movies/movie_confirm_delete.html'
	success_url = reverse_lazy('movies:create_movie')

	def delete(self, request, *args, **kwargs):
		self.object = self.get_object()
		try:
			self.object.delete()
			messages.success(self.request, 'Filme apagado.')
		except ProtectedError:
			messages.error(self.request, 'Você não pode apagar este Filme, foi agendado para assistir')
		return HttpResponseRedirect(self.success_url)


index = MoviesListView.as_view()
add_movie = MovieAddView.as_view()
update_movie = MovieEditView.as_view()
movie_delete = MovieDeleteView.as_view()

app/conf/templates/movies/create_movie.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load formtags %}

{% block navbar %}
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'movies:home' %}">Filmes</a></li> 
        <li class="active"><a href="{% url 'movies:create_movie' %}">Novo</a></li>
      </ul>
      <!--
      <form class="navbar-form navbar-right">
        <input type="text" class="form-control" placeholder="Search...">
      </form>
      -->
    </div>
{% endblock %}

  {% block content %}

<div class="row">
    <div class="col-sm-12 main">

        <h1 class="page-header">Novo</h1>
        <div class="row placeholders">

        <div class="col-xs-6 col-sm-12">



          <form role="form" class="form-horizontal" method="post" enctype="multipart/form-data"><!--form-->
            {% csrf_token %}
        <div class='row'>

          <div class='col-md-4'>
            <div class="form-group {% if form.name.errors %}has-error{% endif %}">
              <label class="col-sm-3 control-label" for="id_name">Nome:</label>
              <div class="col-sm-8">
                {{ form.name|placeholder:"Nome Filme" |addcss:"form-control" }}
                <span class="help-block">{{ form.name.errors|join:"<br \>" }}</span>
              </div>
            </div>
          </div>

          <div class='col-md-4'>
            <div class="form-group {% if form.director.errors %}has-error{% endif %}">
              <label class="col-sm-3 control-label" for="id_director">Diretor:</label>
              <div class="col-sm-8">
                
                {{ form.director|addcss:"form-control" }}
                <span class="help-block">{{ form.director.errors|join:"<br \>" }}</span>
              </div>
            </div>
          </div>

          <div class='col-md-4'>
          <div class="form-group {% if form.img.errors %}has-error{% endif %}">  
          <label class="col-sm-3 control-label" for="id_img">Imagem:</label>
          <div class="col-sm-8">
          <div class="input-group input-file">
            <div class="form-control" style='color:#9C9C9C;'>
              selecione uma imagem
            </div>
            <span class="input-group-addon">
              <a class='btn btn-primary' href='javascript:;'>
                procurar
                <input type="file" od='id_img' name="img" onchange="$(this).parent().parent().parent().find('.form-control').html($(this).val());">
              </a>
            </span>
          </div>
          <span class="help-block">{{ form.img.errors|join:"<br \>" }}</span>
          </div>

          </div>
          </div>

        </div>

        <div class='row'>

          <div class='col-md-4'>
            <div class="form-group {% if form.note.errors %}has-error{% endif %}">
              <label class="col-sm-3 control-label" for="id_note">Nota:</label>
              <div class="col-sm-8">
                {{ form.note|addcss:"form-control" }}
                <span class="help-block">{{ form.note.errors|join:"<br \>" }}</span>
              </div>
            </div>
          </div>

          <div class='col-md-4'>
            <div class="form-group {% if form.description.errors %}has-error{% endif %}">
              <label class="col-sm-3 control-label" for="id_description">Descricao:</label>
              <div class="col-sm-8">
                {{ form.description|textar:"2" |addcss:"form-control" }}
                <span class="help-block">{{ form.description.errors|join:"<br \>" }}</span>
              </div>
            </div>
          </div>

          <div class='col-md-4'>
            <div class="form-group {% if form.status.errors %}has-error{% endif %}">
              <label class="col-sm-3 control-label" for="id_status">Status:</label>
              <div class="col-sm-1">
                {{ form.status }}
                <span class="help-block">{{ form.status.errors|join:"<br \>" }}</span>
              </div>
            </div>
          </div>          


        </div><!--row-->

          <div class='col-md-3 col-md-offset-4' style='margin-top:1%;'>
          <input type="submit" class="btn btn-primary btn-metro" value="Salvar" />
          <a href="{% url 'movies:home' %}" class="btn btn-danger btn-metro" value="voltar" />Voltar</a>

          </div>

          </form><!--form-->
        </div>

          </div>

        </div>
    </div>

<div class="row">
    <div class="col-sm-12 main" style='margin-top:-3%;'>
        <h1 class="page-header">Filmes</h1>
              {% if messages %}
        <div class="row">
          <div class="col-md-6">
            {% for message in messages %}
              <div {% if message.tags == 'error' %} class="alert alert-danger alert-dismissible"{% else %}class="alert alert-info alert-dismissible"{% endif %} role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
                <strong>{{ message.tags }}:</strong> {{ message }}.
              </div>
            {% endfor %}
          </div><!--col-md-6-->
        </div><!--row-->
      {% endif %}

<div class="col-xs-6 col-sm-12">
  <div class="table-responsive">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Nome</th>
          <th>Diretor</th>
          <th>Nota</th>
          <th>Descrição</th>
          <th>Status</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for movies in object_list %}
          <tr>
          <td>{{ movies.name }}</td>
          <td>{{ movies.director }}</td>
          <td>{{ movies.note }}</td>
          <td>{{ movies.description }}</td>
          <td>{% if movies.status %}<span style='color:green;' class="glyphicon glyphicon-ok-sign"></span>{% else %}<span style='color:red;' class="glyphicon glyphicon-minus-sign"></span>{% endif %}</td>  
          <td><a href='{% url 'movies:edit_movie' movies.pk %}'><span class="glyphicon glyphicon-pencil"></span></a></td>
          <td><a href='{% url 'movies:delete_movie' movies.pk %}'><span class="glyphicon glyphicon-remove"></span></a></td>
         
          <tr>              
        {% endfor %}                
      </tbody>
    </table>




          </div>
</div>
       



    </div>


 <!--MODAL INIT-->
  <div id='modal_editar' class="modal fade bs-example-modal-static" tabindex="-1" role="dialog" data-backdrop="static">
    <div class="modal-dialog">
      <div class="modal-content">

        <div class="modal-header">
          <button onclick="set_none('edit')" aria-hidden="true" data-dismiss="modal" class="close" type="button">&times;</button>
          <h4 class="modal-title">Editar {{ object_name }}?</h4>
        </div>

        <div class="modal-body">

          <div id='edit' style="display: none;">
            
          </div>

          <div class='col-md-offset-4'>
            <div id='loading' style="display: none;">
              <img src="{% static "img/carregar.gif" %}" alt="" />
            </div>
          </div>

        </div><!--modal-body-->
      </div><!--modal-content-->
    </div><!--modal-dialog-->
  </div><!--modal-->
  <!--MODAL END-->

 <!--MODAL INIT-->
  <div id='modal_delete' class="modal fade bs-example-modal-static" tabindex="-1" role="dialog" data-backdrop="static">
    <div class="modal-dialog">
      <div class="modal-content">

        <div class="modal-header">
          <button onclick="set_none('delete')" aria-hidden="true" data-dismiss="modal" class="close" type="button">&times;</button>
          <h4 class="modal-title">Apagar {{ object_name }}?</h4>
        </div>

        <div class="modal-body">

          <div id='delete' style="display: none;">
            
          </div>

          <div class='col-md-offset-4'>
            <div id='loading' style="display: none;">
              <img src="{% static "img/carregar.gif" %}" alt="" />
            </div>
          </div>

        </div><!--modal-body-->
      </div><!--modal-content-->
    </div><!--modal-dialog-->
  </div><!--modal-->
  <!--MODAL END-->




</div>




  {% endblock %}


{% block extra_scripts %}
  <script>
 
function send_request(url,id){
  var url = url;
  console.log(url);
  $("#loading").css({display: "block"});

  setTimeout(function(){
    $.ajax({
      type: 'get',
      url: url,
      success: function (data) {
        $("#"+id).html(data);
      },

      error: function (data) {
        $("#"+id).html("Error");
      },

      complete: function(data){
        $("#loading").css({display: "none"});
        $("#"+id).css({display: "block"});
      },
    });
  }, 100);
  return false;
}


function set_none(id){
  $("#"+id).css({display: "none"});
}


</script>
{% endblock %}

app/conf/templates/movies/edit_movie.html
{% extends 'base.html' %}
{% load static %}
{% load formtags %}


{% block navbar %}
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'movies:home' %}">Filmes</a></li> 
        <li class="active"><a href="{% url 'movies:create_movie' %}">Novo</a></li>
      </ul>
      <!--
      <form class="navbar-form navbar-right">
        <input type="text" class="form-control" placeholder="Search...">
      </form>
      -->
    </div>
{% endblock %}

  {% block content %}
<div class="row">
    <div class="col-sm-12 main">

        <h1 class="page-header">Editar?</h1>
              {% if messages %}
        <div class="row">
          <div class="col-md-6">
            {% for message in messages %}
              <div {% if message.tags == 'error' %} class="alert alert-danger alert-dismissible"{% else %}class="alert alert-info alert-dismissible"{% endif %} role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
                <strong>{{ message.tags }}:</strong> {{ message }}.
              </div>
            {% endfor %}
          </div><!--col-md-6-->
        </div><!--row-->
      {% endif %}        
        <div class="row placeholders">

        <div class="col-xs-6 col-sm-12">



          <form role="form" class="form-horizontal" method="post" enctype="multipart/form-data"><!--form-->
            {% csrf_token %}
        <div class='row'>

          <div class='col-md-4'>
            <div class="form-group {% if form.name.errors %}has-error{% endif %}">
              <label class="col-sm-3 control-label" for="id_name">Nome:</label>
              <div class="col-sm-8">
                {{ form.name|placeholder:"Nome Filme" |addcss:"form-control" }}
                <span class="help-block">{{ form.name.errors|join:"<br \>" }}</span>
              </div>
            </div>
          </div>

          <div class='col-md-4'>
            <div class="form-group {% if form.director.errors %}has-error{% endif %}">
              <label class="col-sm-3 control-label" for="id_director">Diretor:</label>
              <div class="col-sm-8">
                
                {{ form.director|addcss:"form-control" }}
                <span class="help-block">{{ form.director.errors|join:"<br \>" }}</span>
              </div>
            </div>
          </div>

          <div class='col-md-4'>
          <div class="form-group {% if form.img.errors %}has-error{% endif %}">  
          <label class="col-sm-3 control-label" for="id_img">Imagem:</label>
          <div class="col-sm-8">
          <div class="input-group input-file">
            <div class="form-control" style='color:#9C9C9C;'>
              selecione uma imagem
            </div>
            <span class="input-group-addon">
              <a class='btn btn-primary' href='javascript:;'>
                procurar
                <input type="file" od='id_img' name="img" onchange="$(this).parent().parent().parent().find('.form-control').html($(this).val());">
              </a>
            </span>
          </div>
          <span class="help-block">{{ form.img.errors|join:"<br \>" }}</span>
          </div>

          </div>
          </div>

        </div>

        <div class='row'>

          <div class='col-md-4'>
            <div class="form-group {% if form.note.errors %}has-error{% endif %}">
              <label class="col-sm-3 control-label" for="id_note">Nota:</label>
              <div class="col-sm-8">
                {{ form.note|addcss:"form-control" }}
                <span class="help-block">{{ form.note.errors|join:"<br \>" }}</span>
              </div>
            </div>
          </div>

          <div class='col-md-4'>
            <div class="form-group {% if form.description.errors %}has-error{% endif %}">
              <label class="col-sm-3 control-label" for="id_description">Descricao:</label>
              <div class="col-sm-8">
                {{ form.description|textar:"2" |addcss:"form-control" }}
                <span class="help-block">{{ form.description.errors|join:"<br \>" }}</span>
              </div>
            </div>
          </div>

          <div class='col-md-4'>
            <div class="form-group {% if form.status.errors %}has-error{% endif %}">
              <label class="col-sm-3 control-label" for="id_status">Status:</label>
              <div class="col-sm-1">
                {{ form.status }}
                <span class="help-block">{{ form.status.errors|join:"<br \>" }}</span>
              </div>
            </div>
          </div>          


        </div><!--row-->

          <div class='col-md-3 col-md-offset-4' style='margin-top:1%;'>
          <input type="submit" class="btn btn-primary btn-metro" value="Alterar" />
          <a href="{% url 'movies:create_movie' %}" class="btn btn-danger btn-metro" value="voltar" />Voltar</a>

          </div>

          </form><!--form-->
        </div>

          </div>

        </div>
    </div>

{% endblock %}

{% block pagination %}
{% endblock %}

app/conf/templates/movies/list_movies.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block navbar %}
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="active"><a href="{% url 'movies:home' %}">Filmes</a></li> 
        <li><a href="{% url 'movies:create_movie' %}">Novo</a></li>
      </ul>
      <form class="navbar-form navbar-right">
        <input name='search' id='search' type="text" class="form-control" placeholder="Pesquisar...">
      </form>
    </div>
{% endblock %}

{% block content %}

<div class="row">
    <div class="col-sm-12 main">

        <h1 class="page-header">Filmes</h1>
        <div class="row placeholders">
        {% for movies in object_list %}
            <div class="col-xs-6 col-sm-3" style='margin-top:2%;'>
                <img src="{{ movies.img.url }}" width="200" height="200" class="img-rounded" alt="Generic placeholder thumbnail">
                <h4>{{ movies.name }}</h4>
                <a  href="{% url 'movies:scheduled_movie' movies.pk %}" class='btn btn-warning'>Agendar</a>
            </div>
        {% empty %}
          <h2>Não há filmes.</h2>            
        {% endfor %}
        </div>

    </div><!-- col-md-12 -->
</div><!-- row -->

{% endblock %}

{% block extra_scripts %}
<script>
  $(function () {
      $.urlParam = function(name){
          var results = new RegExp('[\?&]' + name + '=([^&#]*)').exec(window.location.href);
          if (results==null){
             return null;
          }
          else{
             return results[1] || 0;
          }
      }
      if($.urlParam('search')){
        $('#search').val($.urlParam('search'));
        console.log($.urlParam('search'));  
      }      
  });
</script>
{% endblock %}

app/conf/templates/movies/scheduled_movie.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load formtags %}

{% block navbar %}
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'movies:home' %}">Filmes</a></li> 
        <li><a href="{% url 'movies:create_movie' %}">Novo</a></li>
      </ul>
      <!--
      <form class="navbar-form navbar-right">
        <input type="text" class="form-control" placeholder="Search...">
      </form>
      -->
    </div>
{% endblock %}

  {% block content %}


    <div class="row">
        <div class="col-sm-12 main">

            <h1 class="page-header">Sobre o Filme</h1>
            <div class="row placeholders">

              <div class="col-xs-6 col-sm-12">
              <div class='row'>
              <div class='col-md-2'>
                
                <dl> 
                  <dt><img data-src="holder.js/200x200" class="img-thumbnail" alt="200x200" src="{{ movie.img.url }}"  style="width: 200px; height: 200px;"></dt> 
                  <dt style='margin-top:2%;'>Nome:</dt> 
                    <dd>{{movie.name}}</dd> 
                  <dt>Diretor</dt> 
                    <dd>{{movie.director}}</dd> 
                  <dt>Nota</dt> 
                    <dd>{{movie.note}}</dd>
                  <dt>Status</dt> 
                    <dd>{% if movie.status %}<span style='color:green;' class="glyphicon glyphicon-ok-sign"></span>{% else %}<span style='color:red;' class="glyphicon glyphicon-minus-sign"></span>{% endif %}</dd>
                </dl>
              </div>
              <div class='col-md-10'>
                <p style='text-align:left;'>{{ movie.description }}</p>
              </div>
              </div>

            </div>
        </div>


        </div><!-- col-md-12 -->
    </div><!-- row -->


<div class="row">
    <div class="col-sm-12 main" style='margin-top:-4%;'>

        <h1 class="page-header">Escolher Horário</h1>
        

        <div class="col-xs-6 col-sm-12">

      {% if messages %}
        <div class="row">
          <div class="col-md-6">
            {% for message in messages %}
              <div {% if message.tags %} class="alert alert-{{ message.tags }} alert-dismissible"{% endif %} role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
                <strong>{{ message.tags }}:</strong> {{ message }}.
              </div>
            {% endfor %}
          </div><!--col-md-6-->
        </div><!--row-->
      {% endif %}

          <form role="form" class="form-horizontal" method="post" enctype="multipart/form-data"><!--form-->
            {% csrf_token %}
        <div class='row'>

          <div class='col-md-4'>
            <div class="form-group {% if form.name.errors %}has-error{% endif %}">
              <label class="col-sm-3 control-label" for="id_name">Nome:</label>
              <div class="col-sm-8">
                {{ form.name|placeholder:"Digite seu nome" |addcss:"form-control" }}
                <span class="help-block">{{ form.name.errors|join:"<br \>" }}</span>
              </div>
            </div>
          </div>
        

          <div class='col-md-4'>
            <div class="form-group {% if form.movie.errors %}has-error{% endif %}">
              <label class="col-sm-3 control-label" for="id_movie">Filme:</label>
              <div class="col-sm-8">
                {{ form.movie|addcss:"form-control" }}
                <span class="help-block">{{ form.movie.errors|join:"<br \>" }}</span>
              </div>
            </div>
          </div>
        

          <div class='col-md-4'>
            <div class="form-group {% if form.created_at.errors %}has-error{% endif %}">
              <label class="col-sm-3 control-label" for="id_created_at">Data/Hora:</label>
              <div class="col-sm-8">
                {{ form.created_at|placeholder:"Data/Hora" |addcss:"form-control" }}
                <span class="help-block">{{ form.created_at.errors|join:"<br \>" }}</span>
              </div>
            </div>
          </div>


        </div>  
          <div class='col-md-3 col-md-offset-5' style='margin-top:1%;margin-bottom:5%;'>
          <input type="submit" class="btn btn-primary btn-metro" value="Salvar" />
          <a href="{% url 'movies:home' %}" class="btn btn-danger btn-metro" value="voltar" />Voltar</a>

          </div>                      
      </form>

        </div>
    </div>
</div>


  {% endblock %}

    {% block pagination %}
    {% endblock %}


    {% block extra_scripts %}
        <script type="text/javascript">
            $(function () {
                $('#id_created_at').datetimepicker({locale: 'pt'});
            });
        </script>
    {% endblock %}